### ISSUE TITLE
Atom abaplint update

### ISSUE THREAD

**Issue by ElNovi** [larshp/linter-abaplint#6]
Hi could you please update Atom package? It would be really nice, thanks :)

**Comment by larshp** [comment]
yea, will do, is it currently broken? I updated some stuff in abaplint, so not sure the Atom package works anymore

**Comment by ElNovi** [comment]
No it's not broken, but there lot of unknown statements which i believe you've already added in your other projects (abaplint, and so on ...) . So it just needs updating.

**Comment by larshp** [comment]
by the way, you can also run latest version of abaplint via https://larshp.github.io/abaplint/

however, currently it is not possible to configure the checks in the web version

**Comment by larshp** [comment]
0.11.0 released, try again :smile:
