### ISSUE TITLE
Dependencies not updated

### ISSUE THREAD

**Issue by christian-94** [larshp/linter-abaplint#7]
Not sure about how this thing about dependencies work, but is there a way to configure the ABAP version which you want to lint for?

**Comment by larshp** [comment]
It can be specified when running abaplint via command line. However I do not think I implemented in the Atom package.

![image](https://cloud.githubusercontent.com/assets/5888506/22078075/1f4626ba-ddb7-11e6-8784-d8df967aad36.png)

Also see https://github.com/larshp/abapOpenChecks it implements many of the same checks, and it can be run via Code Inspector inside the ABAP system. It is a lot of work to run all the files through Atom...

**Comment by christian1020-94** [comment]
I get it, I'll take a look at abapOpenChecks.

**Comment by larshp** [comment]
note that the version in abaplint check is only related to the ABAP language statements, not dependencies, example https://larshp.github.io/abaplint/viz/reuse_source.svg
